### ISSUE TITLE
Examples? Axum?

### ISSUE THREAD

**Issue by beckend** [cloudwego/motore#27]

**Comment by PureWhiteWu** [comment]
Hi, could you please provide more information?
Do you want to use motore together with axum?

**Comment by beckend** [comment]
Yes, can we have a layer example used in axum?

**Comment by PureWhiteWu** [comment]
https://github.com/cloudwego/motore/blob/main/motore/src/layer/tower_adapter.rs
Is this what you want? You can try it on main currently.
We will publish a new version in a month.

**Comment by beckend** [comment]
Looks good, but a repo without a clear example folder, you can expect reduced adoption of usage.

**Comment by PureWhiteWu** [comment]
Thank you very much for your suggestion, this is the fact. We have realized this, and we have plan to enhance our document and examples.
