### ISSUE TITLE
Doc URL 404

### ISSUE THREAD

**Issue by caibirdme** [cloudwego/motore#43]
### where's poll_ready
https://www.cloudwego.io/zh/docs/motore/faq/q2_pull_ready/

404

**Comment by Millione** [comment]
Good catch, it should be https://www.cloudwego.io/zh/docs/motore/faq/q1_pull_ready/.

You can submit a PR if you are interested, thanks :)

**Comment by vikigenius** [comment]
@Millione I am still getting 404 error with the new link.

**Comment by GuangmingLuo** [comment]
https://www.cloudwego.io/docs/volo/faq/#where-did-poll_ready-backpressure-go
