### ISSUE TITLE
use stable rust?

### ISSUE THREAD

**Issue by zzzdong** [cloudwego/motore#45]
### Motivation

Sine rust [1.75](https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html) released, can we use stable Rust?

### Proposal

Remove the `rust-toolchain.toml` file and announce the MSRV.

### Alternatives

If we should use nightly, write reason in `README.md`.

**Comment by Millione** [comment]
Good catch. We can use stable Rust now. 

PR is welcomed if you are interested, thanks :)
